
package customer;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Companyname", targetNamespace = "http://customer/", wsdlLocation = "http://laptop-8439rokn:8080/Test/Companyname?wsdl")
public class Companyname_Service
    extends Service
{

    private final static URL COMPANYNAME_WSDL_LOCATION;
    private final static WebServiceException COMPANYNAME_EXCEPTION;
    private final static QName COMPANYNAME_QNAME = new QName("http://customer/", "Companyname");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://laptop-8439rokn:8080/Test/Companyname?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMPANYNAME_WSDL_LOCATION = url;
        COMPANYNAME_EXCEPTION = e;
    }

    public Companyname_Service() {
        super(__getWsdlLocation(), COMPANYNAME_QNAME);
    }

    public Companyname_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMPANYNAME_QNAME, features);
    }

    public Companyname_Service(URL wsdlLocation) {
        super(wsdlLocation, COMPANYNAME_QNAME);
    }

    public Companyname_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMPANYNAME_QNAME, features);
    }

    public Companyname_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Companyname_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Companyname
     */
    @WebEndpoint(name = "CompanynamePort")
    public Companyname getCompanynamePort() {
        return super.getPort(new QName("http://customer/", "CompanynamePort"), Companyname.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Companyname
     */
    @WebEndpoint(name = "CompanynamePort")
    public Companyname getCompanynamePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://customer/", "CompanynamePort"), Companyname.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMPANYNAME_EXCEPTION!= null) {
            throw COMPANYNAME_EXCEPTION;
        }
        return COMPANYNAME_WSDL_LOCATION;
    }

}
