
package customer;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Companyname", targetNamespace = "http://customer/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Companyname {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompanyname", targetNamespace = "http://customer/", className = "customer.GetCompanyname")
    @ResponseWrapper(localName = "getCompanynameResponse", targetNamespace = "http://customer/", className = "customer.GetCompanynameResponse")
    @Action(input = "http://customer/Companyname/getCompanynameRequest", output = "http://customer/Companyname/getCompanynameResponse")
    public List<String> getCompanyname();

}
